### ISSUE TITLE
[TSK] - CONTRIBUTING.md

### ISSUE THREAD

**Issue by samiatoui** [PHACDataHub/DSCO-naming-app#7]
### 📋 Detailed Description

As a Developer, I want a CONTRIBUTING.md file, so that I can I know how to properly contribute to the repo and follow any rules set

```[tasklist]
### ✔️ Tasks
- [x] Create the CONTRIBUTING.md file in the root directory of the repo
- [x] Add information about the branching structure
- [x] Add information about PR linting
- [x] Add information about conventional commit messages
- [x] Provide the basic git workflow
```
